# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: build

on:
  workflow_dispatch:
    branches:
      - master
  
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pybind11
        pip install setuptools wheel twine
    - name: Build
      run: |
        cd x52
        python setup.py sdist bdist_wheel
